My mobile number is <a href="tel:+61435407991">+61435407991</a>, and my email address is <a href="me@willsewell.name">me@willsewell.name</a>.
<br />
<br />
<form id="contact_form">
    Name <input type="text" id="name_text_box" class="text_box">
    <br />
    Your Email <input type="text" id="email_text_box" class="text_box">
    <br />
    Message
    <br />
    <textarea rows="4" cols="50" id="msg_text_area" class="text_box" />
    <br />
    <a class="button" id="contact_submit_button">Submit</a>
</form>
<div id="status_div">Send me a message! Include your email if you want me to reply.<div>