<p>I’ll attempt to keep this professional, but who knows what may end up on here?</p>
<p>Since I haven’t decided what to put here, I’ll just list the open-source
software I used to build this site.</p>
<ul>
    <li>Composer</li>
    <li>Zend Framework 2</li>
    <li>jQuery</li>
    <li>RequireJS</li>
    <li>Pagify</li>
    <li>Sass</p>
</ul>
<p>And some free non-code resources I used:</p>
<ul>
    <li>Subtle Patterns</li>
    <li>Esteban Font</li>
    <li>Merriweather Font</li>
</ul>
<p>And what it’s running on:</p>
<ul>
    <li>Raspberry Pi</li>
    <li>Raspbian</li>
    <li>nginx</li>
    <li>PHP-FPM</li>
    <li>PHP</p>
</ul>
<p>I am obviously incredibly grateful for this!</p>
<p>Everything else is me. Wow… is there much left?</p>