<p>I’ll attempt to keep this professional, but who knows what may end up on here?</p>
<hr />
<p>Since I haven’t decided what to put here, I’ll just list the open-source
software I used to build this site.</p>
<ul>
    <li><a href="http://getcomposer.org/">Composer</a></li>
    <li><a href="http://framework.zend.com/">Zend Framework 2</a></li>
    <li><a href="http://jquery.com/">jQuery</a></li>
    <li><a href="http://requirejs.org/">RequireJS</a></li>
    <li><a href="https://github.com/cmpolis/Pagify">Pagify</a></li>
    <li><a href="http://sass-lang.com/">Sass</a></p>
</ul>
<p>And some free non-code resources I used:</p>
<ul>
    <li><a href="http://subtlepatterns.com/">Subtle Patterns</a></li>
    <li><a href="http://www.google.com/webfonts/specimen/Esteban">Esteban Font</a></li>
    <li><a href="http://www.google.com/fonts/specimen/Merriweather">Merriweather Font</a></li>
</ul>
<p>And what it’s running on:</p>
<ul>
    <li><a href="http://www.raspberrypi.org/">Raspberry Pi</a></li>
    <li><a href="http://www.raspbian.org/">Raspbian</a></li>
    <li><a href="http://nginx.org/">nginx</a></li>
    <li><a href="http://php-fpm.org/">PHP-FPM</a></li>
    <li><a href="http://php.net/">PHP</a>
    <li><a href="http://www.mysql.com/">MySQL</a></li>
</ul>
<p>I am obviously incredibly grateful for these!</p>
<p>Everything else is me. Wow… is there much left?</p>